version: "3.8"
name: "d2b-mq"
services:
  mqnu0145001_iastacceleratorgateway_mr:
    build:
      context: ../mq-container-master
      dockerfile: Dockerfile-server
      target: mq-dev-server
      args:
        MQ_ARCHIVE: downloads/9.4.4.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz
        IMAGE_TAG: ibm-mqadvanced-server-dev:9.4.4.0-arm64
        IMAGE_SOURCE: local
        IMAGE_REVISION: local
        SKIP_TESTS: "true"
    image: ibm-mqadvanced-server-dev:9.4.4.0-arm64
    container_name: mqnu0145001_iastacceleratorgateway_mr_new
    platform: linux/arm64
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/1414"]
      interval: 15s
      timeout: 1m
      retries: 5
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: TESTQMGR
      MQ_ADMIN_PASSWORD: passw0rd
      MQ_APP_PASSWORD: passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - ../container-init/mq/20-config.mqsc:/etc/mqm/20-config.mqsc:ro
    networks:
      - scf_mqnu0145001_iastacceleratorgateway_mr
    restart: unless-stopped

  mqnu0145001_iastacceleratorgateway_mr2:
    build:
      context: ../mq-container-master
      dockerfile: Dockerfile-server
      target: mq-dev-server
      args:
        MQ_ARCHIVE: downloads/9.4.4.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz
        IMAGE_TAG: ibm-mqadvanced-server-dev:9.4.4.0-arm64
        IMAGE_SOURCE: local
        IMAGE_REVISION: local
        SKIP_TESTS: "true"
    image: ibm-mqadvanced-server-dev:9.4.4.0-arm64
    container_name: mqnu0145001_iastacceleratorgateway_mr2_new
    platform: linux/arm64
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/1414"]
      interval: 30s
      timeout: 1m
      retries: 5
      start_period: 2m
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: TESTQMGR2
    ports:
      - "1416:1414"
    command: >
      bash -c "
        /opt/mqm/bin/runmqdevserver &
        sleep 30
        echo 'DEFINE LISTENER(LISTENER.1416) TRPTYPE(TCP) PORT(1416) CONTROL(QMGR) REPLACE' | runmqsc TESTQMGR2
        echo 'START LISTENER(LISTENER.1416)' | runmqsc TESTQMGR2
        wait
      "
    networks:
      - scf_mqnu0145001_iastacceleratorgateway_mr
    restart: unless-stopped

  gonu0145001_iastacceleratorgateway_mr:
    platform: linux/amd64
    image: gonu0145001_iastacceleratorgateway_mr:test
    pull_policy: never
    container_name: gonu0145001_iastacceleratorgateway_mr_new
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/8090"]
      interval: 15s
      timeout: 1m
      retries: 5
    depends_on:
      mqnu0145001_iastacceleratorgateway_mr:
        condition: service_healthy
    ports:
      - "8090:8090"
    networks:
      - scf_mqnu0145001_iastacceleratorgateway_mr
    restart: unless-stopped

networks:
  scf_mqnu0145001_iastacceleratorgateway_mr:
