${UDP_ENPOINT_RESPONSE}#UDP_ENDPOINT_SPR = ${SPR_URI}/ace/spradapter
${UDP_ENPOINT_REQUEST}#UDP_ENDPOINT_PEQ = ${PEQ_URI}/ace/peqadapter/equivalencesmanager
${UDP_ENPOINT_RESPONSE}#UDP_ENDPOINT_PEQ = ${PEQ_URI}/ace/peqadapter/equivalencesmanager
