version: '3.5'

services:
  mq${APPLICATION_NAME}:
    image: mq${APPLICATION_NAME}:test
    container_name: mq${APPLICATION_NAME}
    healthcheck: 
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/1414"]
      interval: 15s
      timeout: 1m
      retries: 5
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "TESTQMGR"
    ports:
      - "${MQ_SERVER_TEST_PORT}:1414"
    networks:
      - ace_mq${APPLICATION_NAME}
    restart: unless-stopped
  aceserver${APPLICATION_NAME}:
    image: ace${APPLICATION_NAME}:test
    container_name: ace${APPLICATION_NAME}
    healthcheck: 
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/7600"]
      interval: 15s
      timeout: 1m
      retries: 5
    depends_on:
      mq${APPLICATION_NAME}:
         condition: service_healthy
    environment:
      LICENSE: "accept"
      ACE_SERVER_NAME: "TEST-SERV"
    ports:
      - "${ACE_WEB_TEST_PORT}:7800"
    networks:
      - ace_mq${APPLICATION_NAME}
    restart: unless-stopped
  go${APPLICATION_NAME}:
    image: go${APPLICATION_NAME}:test
    container_name: go${APPLICATION_NAME}
    healthcheck: 
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/8090"]
      interval: 15s
      timeout: 1m
      retries: 5
    depends_on:
       mq${APPLICATION_NAME}:
          condition: service_healthy
    ports:
      - "${MOCK_WEB_PORT}:8090"   
    networks:
      - ace_mq${APPLICATION_NAME}
    restart: unless-stopped
networks:
  ace_mq${APPLICATION_NAME}:
    driver: bridge