FROM ${ARTIFACTORY_PATH}
RUN useradd -ms /bin/bash ${MQ_USER_D}
#docker build -t tmgtracingmanagergo:test -f Dockerfile_tmg .
COPY tmg/gobinary/ /go/bin/Tracingmanager
COPY tmg/libs/*.so /opt/mqm/lib64/
COPY tmg/libs/*.tbl /opt/mqm/samp/
COPY tmg/libs/runmqakm /opt/mqm/bin/
COPY tmg/libs/gskit8 /opt/mqm/gskit8
COPY tmg/scripts/Ocp_Keystore.sh /usr/local/bin/Ocp_Keystore.sh

RUN mkdir -p /home/${MQ_USER_D}/IBM/MQ/data
COPY tmg/gobinary/mq/mqclient.ini /home/${MQ_USER_D}/IBM/MQ/data/

RUN chown -R ${MQ_USER_D} /go/bin/Tracingmanager /home/${MQ_USER_D}
RUN chmod +x /go/bin/Tracingmanager/${IMAGE_NAME}
RUN chmod +x /usr/local/bin/Ocp_Keystore.sh
RUN chmod -R 755 /opt/mqm/

USER ${MQ_USER_D}

ENTRYPOINT ["sh", "-c", "/go/bin/Tracingmanager/${IMAGE_NAME} -mquser ${MQ_USER_D} -keypass 12345678 -cerpath path -maykey ${QMGR_LABEL}"]