FROM --platform=linux/amd64 ubuntu:jammy-20250819

RUN apt-get update && apt-get install -y \
    libc6 \
    && rm -rf /var/lib/apt/lists/*

COPY --chown=1001 go /go/bin/ModularTest
COPY --chown=1001 go/resources/*.so /opt/mqm/lib64/
COPY --chown=1001 go/resources/*.tbl /opt/mqm/samp/

RUN mkdir -p /IBM/MQ/data/errors
RUN mkdir -p //.mqm
RUN chmod -R 755 /go/bin/ModularTest/modularTesting /IBM //.mqm
ENV LD_LIBRARY_PATH=/opt/mqm/lib64:$LD_LIBRARY_PATH
WORKDIR /go/bin/ModularTest
USER 1001
CMD ["/go/bin/ModularTest/modularTesting"]
