version: '3.5'

services:
  mq${APPLICATION_NAME}:
    image: mq${APPLICATION_NAME}:test
    container_name: mq${APPLICATION_NAME}
    healthcheck: 
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/1414"]
      interval: 15s
      timeout: 1m
      retries: 5
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "TESTQMGR"
    ports:
      - "${MQ_SERVER_TEST_PORT}:1414"
    networks:
      - tmg_mq${APPLICATION_NAME}
    restart: unless-stopped
  tmg${APPLICATION_NAME}:
    image: tmg${APPLICATION_NAME}:test
    container_name: tmg${APPLICATION_NAME}
    healthcheck: 
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9483"]
      interval: 15s
      timeout: 1m
      retries: 5
    depends_on:
       mq${APPLICATION_NAME}:
          condition: service_healthy
    ports:
      - "${TMG_PORT}:9483"   
    networks:
      - tmg_mq${APPLICATION_NAME}
    restart: unless-stopped
networks:
  tmg_mq${APPLICATION_NAME}:
    driver: bridge